### ISSUE TITLE
Not obvious double click on the Playground

### ISSUE THREAD

**Issue by dandelion-lowcode** [eclipse/epsilon-website#25]
Just discovered by pure chance that double clicking on a playground panel maximizes it - it is not obvious from the UI that this feature exists. Could that be signaled somehow graphically?

**Comment by kolovos** [comment]
Also middle-click closes (hides) playground panels. This is inspired by IDEs such as Eclipse and IntelliJ. We could add tooltips to panels (e.g. double-click to maximise, middle-click to close) but they could get disruptive after using the Playground for a while. We should definitely add a note to https://eclipse.dev/epsilon/doc/articles/playground/ though!
