### ISSUE TITLE
Undocumented functions

### ISSUE THREAD

**Issue by dandelion-lowcode** [eclipse/epsilon-website#29]
Some functions are not mentioned in the documentation, namely:

- [x] `asVar`, which is used in a Playground example https://eclipse.dev/epsilon/playground/?flexmi-templates, but yields 0 documentation results https://github.com/search?q=repo%3Aeclipse%2Fepsilon-website%20asVar&type=code. 
- [x] `instanceOf`, used at the last code excerpt at https://eclipse.dev/epsilon/doc/epl/#interoperability-with-other-model-management-tasks. It yields 0 documentation results: https://github.com/search?q=repo%3Aeclipse%2Fepsilon-website+instanceOf&type=code. Anecdotally, I once Ctrl+F'ed "instanceOf" in [EOL's language reference](https://eclipse.dev/epsilon/doc/eol/) unsuccessfully, and had to scroll through the article to remind myself of isKind/TypeOf. 
- [x] I have also found inconsistencies in the operations and character sets between the [EMG article](https://eclipse.dev/epsilon/doc/emg/#emg-predefined-operations) and 2.4.0 API, but cannot pinpoint them off the top of my head.

**Comment by kolovos** [comment]
Thanks for reporting these! I've added the two EOL operations and fixed `nextCamelCaseString` and `nextCamelCaseString` in the EMG documentation page.
